# Configuration and information used across the site
# Remember: not reloaded automatically when changed.

# Site data
title: Dylan Gattey
email: hi@dylangattey.com
author: dgattey
github:  dgattey
description: "Hello! I'm Dylan. I'm a full-stack software engineer + technical lead working for LinkedIn in San Francisco, passionate about well-designed interfaces and clean code."
logo: favicon-512.png
social:
  links:
    - https://www.linkedin.com/in/dgattey
    - https://github.com/dgattey

# Fonts - if changing this, change the SCSS variables too!!
font_url: https://use.typekit.net/ytv4uxf.css
use_font_loader: false # whether or not to use async JS to load font

# Breakpoints - if changing these, change the SCSS variables too!!
breakpoint_min_tablet: 600px
breakpoint_min_desktop: 900px

# Configuration for site
url: "https://dylangattey.com"
permalink: /projects/:title/ #posts
baseurl: ""
google_site_verification: U6mU3aPeTRaCoewYQype946HD1HrM9vY96GoEHKCAnc
preconnect: 
  - https://use.typekit.net
  - https://p.typekit.net
  - https://www.google-analytics.com
  - https://d33wubrfki0l68.cloudfront.net

# Manifest
lang: en
app_theme_color: 1CD1A5
app_background_color: FFFFFF
app_display: standalone
short_title: dg

# Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-25241680-2

# Assets
assets:
  digest: true
  compression: true
  source_maps: false
  sources:
    - _assets/icons
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
favicons:
  generic: [32, 57, 76, 96, 128, 196, 228]
  android: [196]
  ios: [120, 152, 180]
  windows: [144]
  thumbnail: [152]
jekyll-minifier:
  # Because Google Analytics is already minified, we
  # must disable Uglify cause it doesn't play well
  # with an already minified script :(
  compress_javascript: false

# Workbox settings for Service worker
workbox:
  precache_glob_directory: /
  precache_glob_patterns:
    - "assets/*.{js,css,svg,json}"
    - index.html
    - about/index.html
    - /404.html
    - /offline/index.html

# Build settings
markdown: kramdown
source: src
destination: build
include: [static, .htaccess]
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style:  expanded
  deploy_style: compressed

# Plugins
plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-workbox-plugin
  - autoprefixer-rails
