default-src:
  - &self "'self'"
  - &netlify-cdn https://d33wubrfki0l68.cloudfront.net/
  - &netlify https://dgattey.netlify.com/
img-src:
  - *self
  - *netlify
  - *netlify-cdn
  - &google-analytics https://www.google-analytics.com
  - https://google-analytics.com
  - https://www.google.com/ads/
  - https://stats.g.doubleclick.net/
script-src:
  - *self
  - *netlify
  - *netlify-cdn
  - *google-analytics
  - https://google-analytics.com
  - "'sha256-AP5dd2QsbU3QOEJPw+ytEwxizO0kXXheCb4T/H9jz4I='"
  - "'sha256-E0EZj2xhUMF2eiGjBZ7EEtOpOdVx9Ia2ykjanm799ww='"
  # If async google fonts is on, this is it
  #- "'sha256-xXkeCOd4qqYaG8F+aZPKXacPfCWyAHihzqN9OqgGAds='"
connect-src:
  - *netlify
  - *netlify-cdn
  - https://fonts.googleapis.com
  - https://www.google-analytics.com
style-src:
  - *self
  - *netlify
  - *netlify-cdn
  - "'unsafe-inline'"
  - https://fonts.googleapis.com/css
font-src:
  - *self
  - *netlify
  - *netlify-cdn
  - https://fonts.gstatic.com
manifest-src:
  - *self
  - *netlify
  - *netlify-cdn